version: "3.8"
services:
    cloud-web1:
        image: "jelenagaric/cloud-computing:latest"
        restart: unless-stopped
        container_name: cloud-web1
        depends_on:
            - cloud-db1
    cloud-db1:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        restart: unless-stopped
        container_name: cloud-db1
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
    cloud-web2:
        image: "jelenagaric/cloud-computing:latest"
        restart: unless-stopped
        container_name: cloud-web2
        depends_on:
            - cloud-db2
    cloud-db2:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        restart: unless-stopped
        container_name: cloud-db2
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup,,
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - "8000:80"
      
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: