version: "3.8"
services:
    cloud-web:
        build: ./Cloud-Computing
        restart: unless-stopped
        container_name: cloud-web
        depends_on:
            - cloud-db
    cloud-db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        restart: unless-stopped
        container_name: cloud-db
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
        
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - "8000:80"
      
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: